### ISSUE TITLE
Partial updates for existing documents

### ISSUE THREAD

**Issue by VasileCuzmin** [Azure-Samples/azure-search-dotnet-samples#105]
How about an example of updating an existing document partially? 

Thank you

**Comment by HeidiSteen** [comment]
Did you see this article:  https://learn.microsoft.com/en-us/azure/search/search-howto-dotnet-sdk#load-an-index

It shows the IndexDocumentsAction.Upload API, but these APIs would be called in a similar way: IndexDocumentsAction.Merge, IndexDocumentsAction.MergeOrUpload
