### ISSUE TITLE
Directions for ConfigurationSetup()

### ISSUE THREAD

**Issue by marktab** [Azure-Samples/azure-search-dotnet-samples#22]
For https://github.com/Azure-Samples/azure-search-dotnet-samples/tree/master/index-backup-restore

The tags for the configuration setup are not correct -- should be (from code):

            **SourceSearchClient** = new SearchServiceClient(SourceSearchServiceName, new SearchCredentials(SourceAdminKey));
            **SourceIndexClient** = SourceSearchClient.Indexes.GetClient(SourceIndexName);

            **TargetSearchClient** = new SearchServiceClient(TargetSearchServiceName, new SearchCredentials(TargetAdminKey));
            **TargetIndexClient** = TargetSearchClient.Indexes.GetClient(TargetIndexName);

**Comment by brjohnstmsft** [comment]
@marktab What do you mean by tags exactly? Is the issue in the code, the Readme file...? More info is necessary for us to take action on this. Or, you could submit a pull request.

**Comment by marktab** [comment]
@brjohnstmsft  I responded in Teams with pictures -- the suggestion is minor, but technically important

**Comment by brjohnstmsft** [comment]
The typos in the readme have been fixed.
