### ISSUE TITLE
Wondering when this will be migrated?

### ISSUE THREAD

**Issue by ANSCERS** [Azure-Samples/azure-search-dotnet-samples#3]
Really looking for some getting started samples.  

Thanks,
Therese

**Comment by brjohnstmsft** [comment]
@ANSCERS We're still working on migrating the existing samples as well as writing new ones, but in the meantime you can find the existing samples here: https://github.com/azure-samples/search-dotnet-getting-started

**Comment by ANSCERS** [comment]
Thank you!

I also look forward to your new samples.

**Comment by HeidiSteen** [comment]
New samples are now in this repo.
