### ISSUE TITLE
Issue while deploying static web app

### ISSUE THREAD

**Issue by sagar2503** [Azure-Samples/azure-search-dotnet-samples#90]
While deploying Static web app and function , it did not show me below prompt

**Select the location of your Azure Function code**

Hence it did not deploy Azure Function

**Comment by MatthieuLefebvre** [comment]
it's already part of the yaml file but you have to change the "\" by a "/" in the row 31 then commit and push again to make sure the api will be well deployed.

**Comment by HeidiSteen** [comment]
There were issues with the VS Code extension for Static Web Apps.  The sample and docs have been fixed.
